name: 刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.wx }}'
          pkey='${{ secrets.SCT204185Ty0KyUUyBDfhKwZOpXoDJMd0l }}'
          user='${{ secrets.wenjing_he@ctgu.edu.cn }}'
          pwd='${{ secrets.hewenjing221 }}'
          step='${{ secrets.23069 }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
